[api]
  dashboard = true

[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[providers.docker]

[providers.file]
  directory = "/etc/traefik"
  watch = true

[certificatesResolvers.cloudflare.acme]
  email = "admin@domain.com"
  [certificatesResolvers.cloudflare.acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 0

[certificatesResolvers.letsencrypt.acme]
  email = "admin@domain.com"
  storage = "acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web"